# Kitty Theme: White-on-Black
foreground            #ffffff
background            #000000
background_opacity    0.8
cursor               #d4af37
selection_foreground  #000000
selection_background  #d4af37

# ANSI Colors
# Black
color0  #000000
color8  #1a1a1a

# Red
color1  #cc3333
color9  #ff3333

# Green
color2  #ffffff
color10 #f0f0f0

# Yellow
color3  #d4af37
color11 #e5c05a

# Blue
color4  #cccccc
color12 #dddddd

# Magenta
color5  #870087
color13 #af00af

# Cyan
color6  #eeeeee
color14 #ffffff

# White
color7  #ffffff
color15 #ffffff

